esphome:
  name: smart-signage
  libraries:
    - "https://github.com/ETLCPP/etl.git"

esp32:
  board: seeed_xiao_esp32s3
  framework:
    type: esp-idf

logger:
  level: DEBUG

# Enable Home Assistant API
# api:
#   password: ""

# ota:
#   - platform: esphome
#     password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none 
  ap:
    ssid: "smart-signage"
    password: "ss123456"

captive_portal:

web_server:
  port: 80

# ───── Dashboard knobs/sliders (stored in NVS) ─────
number:
  - platform: template
    name: "Presence Radius (meter)"
    id: radius_num
    optimistic: true
    restore_value: true
    min_value: 1
    max_value: 6
    step: 1
    set_action:
      - lambda: |-
          id(radius_num).publish_state(x);   // persist
          id(ss1)->set_radius(x);            // forward to C++

  - platform: template
    name: "Monitoring Period (hrs)"
    id: duration_num
    optimistic: true
    restore_value: true
    min_value: 0
    max_value: 24
    step: 0.5
    set_action:
      - lambda: |-
          id(duration_num).publish_state(x);
          id(ss1)->set_duration(x);

  - platform: template
    name: "Volume (%)"
    id: volume_num
    optimistic: true
    restore_value: true
    min_value: 0
    max_value: 100
    step: 1
    set_action:
      - lambda: |-
          id(volume_num).publish_state(x);
          id(ss1)->set_volume(x);

  - platform: template
    name: "Brightness (%)"
    id: brightness_num
    optimistic: true
    restore_value: true
    min_value: 0
    max_value: 100
    step: 1
    set_action:
      - lambda: |-
          id(brightness_num).publish_state(x);
          id(ss1)->set_brightness(x);

# ───── Dashboard start push-button (momentary) ─────
button:
  - platform: template
    name: "Signage Start"
    id: start_button
    on_press:
      - lambda: "id(ss1)->on_start_button();"

external_components:
  - source: components        # your smart_signage folder

smart_signage:
  id: ss1
  radius_number: radius_num
  duration_number: duration_num
  volume_number: volume_num
  brightness_number: brightness_num
  start_button: start_button
