esphome:
  name: smart-signage
  platformio_options:
    platform: https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21/platform-espressif32.zip
    lib_ldf_mode: deep
    board_build.filesystem: littlefs
    board_build.partitions: "../../../custom_partitions.csv" # absolute path doesnt work, 
    build_flags:
      - -DCORE_DEBUG_LEVEL=2        # lower noise to help audio quality
      - -Wno-unused-variable
      - -Wno-unused-but-set-variable
      - -Wno-unused-function
      - -Wno-format-extra-args
    
  libraries:
    - "https://github.com/ETLCPP/etl.git"
    - "iavorvel/MyLD2410@^1.2.5"
    - "denyssene/SimpleKalmanFilter"
    - "https://github.com/LiquidCGS/FastIMU.git#1.2.8"
    - "hideakitai/ArduinoEigen@^0.3.2"
    - "https://github.com/pschatzmann/arduino-audio-tools.git"
    - "https://github.com/pschatzmann/arduino-libhelix.git"
  includes:
    - components/smart_signage/include/


esp32:
  board: seeed_xiao_esp32s3
  flash_size: 8MB
  framework:
    type: arduino
    version: 3.2.1


logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none 
  ap:
    ssid: "smart-signage"
    password: "ss123456"

captive_portal:

web_server:
  port: 80

# ───────────────────────────── Smart-signage component ─────────────────────
smart_signage:
  id: ss1
  currProfile:    currProfile
  sessionMins:    sessionMins
  radarRangeCm:   radarRangeCm
  audioVolPct:    audioVolPct
  ledBrightPct:   ledBrightPct
  startButton:    startButton

  
  profileCatalog:  !include profile_catalog.yaml
# ───────────────────────────── Dashboard entities ──────────────────────────
select:
  - platform: template
    name: "Profile"
    id: currProfile
    optimistic: true
    options:
      - "__placeholder__"

  - platform: template
    name: "Knob Function"
    id: knobFn
    optimistic: true
    restore_value: true
    options:
      - "Session Period (hrs)"
      - "Detection Radius (m)"
      - "Speaker Volume (%)"
      - "LED Brightness (%)"

number:
  - platform: template
    name: "Session Period (hrs)"
    id: sessionMins
    optimistic: true
    restore_value: true
    min_value: 0
    max_value: 24
    step: 0.5

  - platform: template
    name: "Detection Radius (m)"
    id: radarRangeCm
    optimistic: true
    restore_value: true
    min_value: 1
    max_value: 6
    step: 1

  - platform: template
    name: "Speaker Volume (%)"
    id: audioVolPct
    optimistic: true
    restore_value: true
    min_value: 0
    max_value: 100
    step: 1

  - platform: template
    name: "LED Brightness (%)"
    id: ledBrightPct
    optimistic: true
    restore_value: true
    min_value: 0
    max_value: 100
    step: 1

button:
  - platform: template
    name: "Start"
    id: startButton


binary_sensor:
  - platform: gpio
    pin:
      number: 4
      mode: INPUT_PULLUP
      inverted: true
    name: "Physical Start Button"
    on_press:
      then:
        - button.press: startButton

external_components:
  - source: components      # ← folder that holds this component
