esphome:
  name: smart-signage
  libraries:
    - "https://github.com/ETLCPP/etl.git"
  includes:
    - components\smart_signage\include\


esp32:
  board: seeed_xiao_esp32s3
  flash_size: 8MB
  partitions: "custom_partitions.csv"
  framework:
    type: esp-idf
    components:
      - name: esp_littlefs
        source: https://github.com/joltwallet/esp_littlefs.git


logger:
  level: DEBUG

# Enable Home Assistant API
# api:
#   password: ""

# ota:
#   - platform: esphome
#     password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none 
  ap:
    ssid: "smart-signage"
    password: "ss123456"

captive_portal:

web_server:
  port: 80

# ───────────────────────────── Smart-signage component ─────────────────────
smart_signage:
  id: ss1
  currProfile:    currProfile
  knobFn:         knobFn
  sessionMins:    sessionMins
  radarRangeCm:   radarRangeCm
  audioVolPct:    audioVolPct
  ledBrightPct:   ledBrightPct
  startButton:    startButton

  
  profileConfig:  !include profile_config.yaml
# ───────────────────────────── Dashboard entities ──────────────────────────
select:
  - platform: template
    name: "Profile"
    id: currProfile
    optimistic: true
    options:
      - "__placeholder__"


  - platform: template
    name: "Knob Fn"
    id: knobFn
    optimistic: true
    options:
      - "__placeholder__"

number:
  - platform: template
    name: "Session Period (mins)"
    id: sessionMins
    optimistic: true
    restore_value: true
    min_value: 0
    max_value: 24
    step: 0.5

  - platform: template
    name: "Detection Radius (m)"
    id: radarRangeCm
    optimistic: true
    restore_value: true
    min_value: 1
    max_value: 6
    step: 1

  - platform: template
    name: "Speaker Volume (%)"
    id: audioVolPct
    optimistic: true
    restore_value: true
    min_value: 0
    max_value: 100
    step: 1

  - platform: template
    name: "LED Brightness (%)"
    id: ledBrightPct
    optimistic: true
    restore_value: true
    min_value: 0
    max_value: 100
    step: 1

button:
  - platform: template
    name: "Start"
    id: startButton

external_components:
  - source: components      # ← folder that holds this component
